/**
 * 8WHIE VoiceForge - Language Registry
 * Copyright © 2026 8WHIE / Aryan Thakur. All rights reserved.
 */

import { LanguageInfo, SupportedLanguage } from '../types/tts';

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    family: 'Indo-European (Germanic)',
    script: 'Latin',
    sampleText: 'Welcome to 8WHIE VoiceForge. Natural speech synthesis powered by modern acoustic architecture.',
    phonemeSupport: true,
  },
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    family: 'Indo-Aryan',
    script: 'Devanagari',
    sampleText: '8WHIE वॉइसफोर्ज में आपका स्वागत है। यह एक आधुनिक और प्राकृतिक वाक् संश्लेषण प्रणाली है।',
    phonemeSupport: true,
  },
  {
    code: 'hinglish',
    name: 'Hinglish',
    nativeName: 'Hinglish (Hindi in Latin script)',
    family: 'Hybrid Indo-Aryan / Germanic',
    script: 'Latin (Transliterated)',
    sampleText: '8WHIE VoiceForge me aapka swagat hai. Aaj hum AI voice design aur natural speech explore karenge.',
    phonemeSupport: true,
  },
  {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    family: 'Indo-Aryan',
    script: 'Bengali',
    sampleText: '8WHIE ভয়েসফোর্জে আপনাকে স্বাগতম। এটি একটি উন্নত বহুভাষিক স্পিচ জেনারেশন প্ল্যাটফর্ম।',
    phonemeSupport: true,
  },
  {
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    family: 'Indo-Aryan',
    script: 'Devanagari',
    sampleText: '8WHIE व्हॉइसफोर्जमध्ये आपले स्वागत आहे. अचूक उच्चार आणि नैसर्गिक संवाद तंत्रज्ञान.',
    phonemeSupport: true,
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    family: 'Dravidian',
    script: 'Tamil',
    sampleText: '8WHIE வாய்ஸ்போர்ஜ் உங்களை வரவேற்கிறது. துல்லியமான மற்றும் இயற்கையான குரல் உற்பத்தி.',
    phonemeSupport: true,
  },
  {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    family: 'Dravidian',
    script: 'Telugu',
    sampleText: '8WHIE వాయిస్‌ఫోర్జ్‌కి స్వాగతం. ఆధునిక బహుభాషా ధ్వని సంశ్లేషణ వేదిక.',
    phonemeSupport: true,
  },
  {
    code: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    family: 'Indo-Aryan',
    script: 'Gujarati',
    sampleText: '8WHIE વોઇસફોર્જમાં તમારું સ્વાગત છે. અદ્યતન એઆઈ આધારિત અવાજ પેદા કરવાની સિસ્ટમ.',
    phonemeSupport: true,
  },
  {
    code: 'pa',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    family: 'Indo-Aryan',
    script: 'Gurmukhi',
    sampleText: '8WHIE ਵਾਇਸਫੋਰਜ ਵਿੱਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ। ਬਹੁ-ਭਾਸ਼ਾਈ ਕੁਦਰਤੀ ਆਵਾਜ਼ ਸੰਸਲੇਸ਼ਣ ਪਲੇਟਫਾਰਮ।',
    phonemeSupport: true,
  },
  {
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    family: 'Indo-Aryan',
    script: 'Nastaliq / Arabic',
    sampleText: '8WHIE وائس فورج میں خوش آمدید۔ کثیر لسانی قدرتی صوتی پیداوار کا ایک جدید پلیٹ فارم۔',
    phonemeSupport: true,
  },
  {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    family: 'Indo-European (Romance)',
    script: 'Latin',
    sampleText: 'Bienvenidos a 8WHIE VoiceForge. Generación de voz natural y expresiva para creadores modernos.',
    phonemeSupport: true,
  },
  {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    family: 'Indo-European (Romance)',
    script: 'Latin',
    sampleText: 'Bienvenue sur 8WHIE VoiceForge. Synthèse vocale multilingue avec contrôle acoustique précis.',
    phonemeSupport: true,
  },
  {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    family: 'Indo-European (Germanic)',
    script: 'Latin',
    sampleText: 'Willkommen bei 8WHIE VoiceForge. Fortschrittliche Sprachgenerierung mit natürlicher Betonung.',
    phonemeSupport: true,
  },
  {
    code: 'pt',
    name: 'Portuguese',
    nativeName: 'Português',
    family: 'Indo-European (Romance)',
    script: 'Latin',
    sampleText: 'Bem-vindo ao 8WHIE VoiceForge. Síntese de voz com modulação emocional e sotaques autênticos.',
    phonemeSupport: true,
  },
  {
    code: 'it',
    name: 'Italian',
    nativeName: 'Italiano',
    family: 'Indo-European (Romance)',
    script: 'Latin',
    sampleText: 'Benvenuti in 8WHIE VoiceForge. Una piattaforma all’avanguardia per la voce sintetica naturale.',
    phonemeSupport: true,
  },
  {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    family: 'Afroasiatic (Semitic)',
    script: 'Arabic',
    sampleText: 'مرحباً بكم في 8WHIE VoiceForge. منصة متقدمة لتوليد الصوت البشري الطبيعي متعدد اللغات.',
    phonemeSupport: true,
  },
  {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    family: 'Japonic',
    script: 'Kanji / Hiragana / Katakana',
    sampleText: '8WHIE VoiceForgeへようこそ。自然で表現力豊かな多言語音声合成プラットフォームです。',
    phonemeSupport: true,
  },
  {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    family: 'Koreanic',
    script: 'Hangul',
    sampleText: '8WHIE VoiceForge에 오신 것을 환영합니다. 자연스러운 음성과 표현력을 지원하는 음성 플랫폼입니다.',
    phonemeSupport: true,
  },
];

export function getLanguageInfo(code: SupportedLanguage): LanguageInfo {
  return SUPPORTED_LANGUAGES.find((l) => l.code === code) || SUPPORTED_LANGUAGES[0];
}
